### PR TITLE
Custom Fabled

### LINKED ISSUE #110: Feature Request: Custom Fabled
**Is your feature request related to a problem? Please describe.**
Homebrew scripts currently can add custom character types, custom characters, script icon etc, but does not support adding custom Fabled.
Custom Fabled can allow script makers to describe their homebrew rules in a more convenient manner, or just to allow players to try out various Fabled ideas that are floating around.

**Describe the solution you'd like**
When a custom script is uploaded, characters which have the "team": "fabled" should be added to active fabled list.

### PR DESCRIPTION
**Pull request by bra1n**
closes #110

### CODE REVIEW

**Comment by davotronic5000** [comment]
Code looks great all seems to work correctly, I think the only suggestions I would make are:
1. Custom fabled currently get a traveler style default image, would be nice if that was in the fabled gold style.
2. A small update to the readme.md to add "fabled" as an option for the team string in the Custom Character support documentation.

**Comment by bra1n** [comment]
Great suggestions! As soon as I have a bit more time, I'll implement both. 😄

**Comment by bra1n** [comment]
@davotronic5000 can be re-reviewed :)

**Review by davotronic5000 — APPROVED** [review]
All good now, perfect.

**Pull request merged**
