### PR TITLE
Remove NightReminders for entries with night value 0

### PR DESCRIPTION
**Pull request by AWConant**
These can never appear so long as the associated `firstNight`/`otherNight` value is 0, so they are dead weight that can be removed. They can be resurrected from history in the future if needed.

### CODE REVIEW

**Comment by AWConant** [comment]
(I assume this is not interesting enough to include in the changelog)

**Comment by bra1n** [comment]
So this does look like a bug, but one that should actually show night reminders. I pinged @eddgabriel to take a look at it and hopefully assign some non-zero values here. :)

**Comment by AWConant** [comment]
It looks like the script tool does not generate any of the night entries removed in this PR with the following exceptions:

- Leviathan should have an otherNights entry (after dawn, if that's technically feasible)
- Pixie should have an otherNight entry

Some of these, like Flowergirl/Town Crier are not actual night actions, but the (helpful) reminder to initialize the "didn't nominate/vote" state may have crept in from Ben Finney's homemade docs or from secret internal docs (maybe the unreleased, published version of the night order has these).

Others, like Tinker/Acrobat are probably just bugs, as it seems (so far) like a strong invariant that no one dies night 1.

**Comment by eddgabriel** [comment]
I actually had the Acrobat note on there because the original Acrobat could die N1, it's since changed to only be each night*. Tinker can still technically die N1, but there's no reminder on the night sheet for it. I'm working on correcting the others shortly.

**Comment by AWConant** [comment]
I can't imagine a night reminder for the Tinker to die N1 would cause anything but suffering.

**Comment by bra1n** [comment]
Closed by #186

**Pull request closed without merging**
